query Product($slug: String) {
  product(slug: $slug) {
    productId
    productName
    productReference
    brand
    description
    items {
      itemId
      name
      images {
        imageId
        imageLabel
        imageTag
        imageUrl
        imageText
      }
      sellers {
        sellerId
        sellerName
        addToCartLink
        sellerDefault
        commertialOffer {
          Installments {
            Value
            InterestRate
            TotalValuePlusInterestRate
            NumberOfInstallments
            Name
          }
          Price
          ListPrice
        }
      }
    }
    properties {
      name
      values
    }
  }
}
