query Product($slug: String) {
  product(slug: $slug) {
    productId
    productName
    brand
    description
    items {
      itemId
      name
      images {
        imageId
        imageLabel
        imageTag
        imageUrl
        imageText
      }
      sellers {
        sellerId
        sellerName
        addToCartLink
        sellerDefault
        commertialOffer {
          Price
          ListPrice
        }
      }
    }
  }
}
